# Generated by Django 3.2.9 on 2021-12-12 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='description',
            new_name='bio',
        ),
        migrations.AddField(
            model_name='dog',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='BirthDay'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='fav_snack',
            field=models.CharField(default='nuggies', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='hobbies',
            field=models.TextField(default='nuggies', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='postal_code',
            field=models.CharField(default='nuggs', max_length=7),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=7)),
                ('bio', models.TextField(max_length=250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('image', models.CharField(max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.dog')),
            ],
        ),
    ]
