# Generated by Django 3.2.9 on 2021-12-12 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211211_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='user',
        ),
        migrations.AddField(
            model_name='dog',
            name='profile',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
            preserve_default=False,
        ),
    ]
