# Generated by Django 3.2.9 on 2021-12-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211213_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='postal_code',
        ),
    ]
