# Generated by Django 3.2.9 on 2021-12-14 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 14, 16, 28, 35, 443177)),
        ),
        migrations.AlterField(
            model_name='dog',
            name='birthday',
            field=models.DateField(verbose_name='Birthday'),
        ),
    ]
